replaced studly_case() with Str::studly
After upgrading to laravel 6, i got this error for all tests that involved model validation:
Error: Call to undefined function Watson\Validating\studly_case()

I'm new to Laravel but googled a bit and was able to pass the tests with the above fix. hope it's correct.